DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	seq     	BIGINT		NOT NULL AUTO_INCREMENT,
	userid 		varchar(50) 	NOT NULL,
	email 		varchar(50) 	NOT NULL,
	passwd   	varchar(80) 	NOT NULL,
	LOGIN_COUNT 	int 	 NOT NULL DEFAULT 0,
	LAST_LOGIN_AT 	datetime 	  DEFAULT NULL,	
	CREATE_AT 	datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(seq),
	CONSTRAINT unq_user_email UNIQUE(email)
);


 INSERT INTO USERS(USERID, EMAIL, PASSWD, LOGIN_COUNT) VALUES('user1','user1@naver.com','1234',1);
 INSERT INTO USERS(USERID, EMAIL, PASSWD, LOGIN_COUNT) VALUES('user2','user2@naver.com','1234',1);
 INSERT INTO USERS(USERID, EMAIL, PASSWD, LOGIN_COUNT) VALUES('user3','user3@naver.com','1234',1);
 INSERT INTO USERS(USERID, EMAIL, PASSWD, LOGIN_COUNT) VALUES('user4','user4@naver.com','1234',1);

